SOURCES =
SOURCES += sources/checks/check_lines.c
SOURCES += sources/checks/ckeck_params.c
SOURCES += sources/checks/is_map_valid.c
SOURCES += sources/display/display_map.c
SOURCES += sources/errors/print_errors.c
SOURCES += sources/main.c
SOURCES += sources/process/ft_file_save.c
SOURCES += sources/process/ft_file_to_tab.c
SOURCES += sources/process/ft_process.c
SOURCES += sources/process/ft_stdin_save.c
SOURCES += sources/process/recreate_map.c
SOURCES += sources/str_tools/cat_first_params.c
SOURCES += sources/str_tools/ft_atoi.c
SOURCES += sources/str_tools/ft_putchar.c
SOURCES += sources/str_tools/ft_putstr.c
SOURCES += sources/str_tools/ft_strcmp.c
SOURCES += sources/str_tools/ft_strlen.c
