SOURCES =
SOURCES += sources/dictionnary/dictionnary_args_checker.c
SOURCES += sources/dictionnary/dictionnary_datas_manager.c
SOURCES += sources/dictionnary/format.c
SOURCES += sources/dictionnary/table_creator.c
SOURCES += sources/error/error.c
SOURCES += sources/main.c
SOURCES += sources/number/number_truncator.c
SOURCES += sources/print_number.c
SOURCES += sources/reader.c
SOURCES += sources/temp.c
SOURCES += sources/utils/malloc_utils.c
SOURCES += sources/utils/str/char_type_checker.c
SOURCES += sources/utils/str/str_utils.c
